Repository rust-ndarray/ndarray-stats, pull requests merged in 2019-04, with the labels that each got.

#25 Histogram error handling
  src/entropy.rs
  src/errors.rs
  src/histogram/errors.rs
  src/histogram/grid.rs
  src/histogram/histograms.rs
  src/histogram/strategies.rs
  src/quantile.rs
  src/summary_statistics/means.rs
  src/summary_statistics/mod.rs
  tests/quantile.rs
Labels: Breaking changes

#23 Central moments
  Cargo.toml
  src/lib.rs
  src/summary_statistics/means.rs
  src/summary_statistics/mod.rs
Labels: Enhancement

#26 Bulk quantiles
  Cargo.toml
  benches/sort.rs
  src/errors.rs
  src/histogram/strategies.rs
  src/lib.rs
  src/quantile/interpolate.rs
  src/quantile/mod.rs
  src/sort.rs
  tests/quantile.rs
  tests/sort.rs
Labels: Breaking changes

#39 Fix get_many_from_sorted_mut benchmark
  benches/sort.rs
Labels: Bug

#37 Make argmin/max_skipnan use EmptyInput error type
  src/quantile/mod.rs
  tests/quantile.rs
Labels: Breaking changes, Enhancement

#38 Prevent other crates from implementing our traits
  src/correlation.rs
  src/entropy.rs
  src/histogram/histograms.rs
  src/lib.rs
  src/maybe_nan/mod.rs
  src/quantile/interpolate.rs
  src/quantile/mod.rs
  src/sort.rs
  src/summary_statistics/means.rs
  src/summary_statistics/mod.rs
Labels: Breaking changes

#40 Update to Rust 2018 and replace quickcheck! with #[quickcheck]
  .travis.yml
  Cargo.toml
  benches/sort.rs
  src/correlation.rs
  src/entropy.rs
  src/errors.rs
  src/histogram/bins.rs
  src/histogram/errors.rs
  src/histogram/grid.rs
  src/histogram/histograms.rs
  src/lib.rs
  src/maybe_nan/impl_not_none.rs
  src/maybe_nan/mod.rs
  src/quantile/mod.rs
  src/sort.rs
  tests/quantile.rs
  tests/sort.rs
Labels: Internal
